version: "3.9"

services:
  web:
    build: .
    container_name: task_manager_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app

  db:
    image: postgres
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password10$
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
